// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/angular'

import _menu_bar from './menu-bar.bones.json'
import _carousel from './carousel.bones.json'
import _product_card from './product-card.bones.json'

configureBoneyard({"color":"#D4D4D4","darkColor":"#2a2a2a","animate":"shimmer","stagger":true,"transition":true})

registerBones({
  "menu-bar": _menu_bar,
  "carousel": _carousel,
  "product-card": _product_card,
})
